replicaCount: 2

image:
  repository: cloudacademydevops/webappecho
  tag: latest
  pullPolicy: Always

env:
  MESSAGE:
    value: "CloudAcademy ❤ DevOps - Dev"
  BACKGROUND_COLOR:
    value: "lime"

service:
  type: ClusterIP
  port: 8080