replicaCount: 4

image:
  repository: cloudacademydevops/webappecho
  tag: latest
  pullPolicy: Always

env:
  MESSAGE:
    value: "CloudAcademy ❤ DevOps - Prod"
  BACKGROUND_COLOR:
    value: "aqua"

service:
  type: ClusterIP
  port: 8080